[WIP] Build Example Notebook to Walk Through mne-hfo usage
adam2392/mne-hfo pull request #10
Opened 2021-02-06 00:40 UTC by pmyers16

PR Description
--------------

Closes: #6 
Closes: #9 

This PR's goal is mostly to build a demo notebook to walk through mne-hfo usage. Some modifications and supporting functions needed to be added along the way.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/adam2392/mne-hfo/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

2021-02-06 15:04 UTC, adam2392 commented on mne_hfo/io.py
> +        The name of the event to add to the "trial_type" column
```suggestion
        The prefix of the channel event to add to the "trial_type" column (e.g. ``hfo`` for channel ``A1``
        would result in ``hfo_A1``).
```

2021-02-06 15:18 UTC, adam2392 commented
Nice, it's not bad start. A few comments:

1. Limit the print statements. It renders as a huge file otw.
2. Include a GridSearchCV/RandomGridSearchCV using metric we converge on (see below). Might need to fenangle the Detector implementation though to improve the `predict` and `score` function.
3. Render the simulated part.

To compare HFO detections, what are you using as a metric? E.g. det1 gets HFO (time_x, time_y) and det2 gets HFO (time_a, time_b). What is the proposed overlap function? 

In https://github.com/adam2392/mne-hfo/issues/9, I guess it is just overlap in endpoints counts as +1, no-overlap at all in endpoints counts as 0. Is that correct? Thus the metric in our case is simply a "custom" accuracy implementation.

Are there any weaknesses to this approach? What other metrics can alleviate that weakness?

### Scoring Function to make SearchCV work

If that's the case, it seems that most of traditional metrics (e.g. accuracy), we have to define ourselves using for example, the overlap incidence defined above. Probably more things, such as roc_auc, etc. I can see the `score` function to simply operate with a kwarg input defining the metric (e.g. `'accuracy'`).

Then, we massage the data to go from these HFO events to our criterion. E.g. For overlap, events gets converted from (time_x, time_y) -> {+1, 0}. So for two running lists of HFO events, we get a list of y_true and y_pred. Then it becomes trivial to feed those to sklearn's API. That way, our responsibility is just implementing the logic to get to `y_true` and `y_pred`.

2021-02-07 17:10 UTC, adam2392 commented
I've added an API to go from `*events.tsv` -> `*annotations.tsv` and corresponding tests for the public functions in ``io.py``. 

Let's get this closed out and refine the example as we develop the API further. Can you do the following:

1. Simplify the jupyter notebook (see comment above) and render the simulation cells as well.
2. Add unit tests for `find_coincident_events` 
3. Update `whats_new.rst` document with a description of what was added here. 

Re-ping me when that's done, and then let's meet to discuss how the algorithms performed on the validation dataset, and how we can start running it on the sickkids dataset.

2021-02-07 18:19 UTC, adam2392 commented on mne_hfo/utils.py
> +def _check_column_types(dfs, cols):
What's the point of this function?

2021-02-07 18:20 UTC, adam2392 commented on mne_hfo/utils.py
> +def _change_duration_to_offset(dfs, cols):
What's the point of this function?

2021-02-07 18:23 UTC, adam2392 commented on mne_hfo/utils.py
> +    Note: Both input dictionaries should come from the same original dataset and therefore contain the same keys
Perhaps add an error check at the beginning for this.

2021-02-07 18:25 UTC, adam2392 commented on mne_hfo/utils.py
> +def _check_column_types(dfs, cols):
Okay I think it means you're trying to check numeric for columns. Change the name to something like `_enforce_numeric_cols`, or something like that.

2021-02-07 19:37 UTC, adam2392 requested changes
I've added an API to go from `*events.tsv` -> `*annotations.tsv` and corresponding tests for the public functions in ``io.py``. 

Let's get this closed out and refine the example as we develop the API further. Can you do the following:

1. Simplify the jupyter notebook (see comment above) and render the simulation cells as well.
2. Add unit tests for `find_coincident_events` 
3. Update `whats_new.rst` document with a description of what was added here. 

Re-ping me when that's done, and then let's meet to discuss how the algorithms performed on the validation dataset, and how we can start running it on the sickkids dataset.

2021-02-08 15:26 UTC, pmyers16 commented on mne_hfo/utils.py
> +def _change_duration_to_offset(dfs, cols):
The current "compare to gold standard" functions use onset and offset columns of a dataframe, but the output dataframes from analysis have onset and duration. This just adds the offset column

2021-02-08 15:47 UTC, adam2392 commented on mne_hfo/utils.py
> +def _change_duration_to_offset(dfs, cols):
Ah I see, rather then pass a list of dataframes(?) and list of columns, perhaps make this more verbose?

def _add_offset_to_df(df):
      # compute offset for one dataframe using onset/duration

Then call it on the outside inside a for loop if you really need to run it on multiple dataframes.

Rn, it seems more general then it should be, and that can lead to errors that are unforseen.

2021-02-09 16:46 UTC, adam2392 commented on docs/whats_new.rst
> +* `Patrick Myers`_
You'll need to add yourself to the `authors.rst` document as well.

2021-02-09 16:53 UTC, adam2392 commented
Fixed circle CI for you.

2021-02-09 20:02 UTC, merged