[WIP] Implement Score so we can perform Gridsearch
adam2392/mne-hfo pull request #15
Opened 2021-02-16 21:06 UTC by pmyers16

Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/adma2392/mne-hfo/blob/master/CONTRIBUTING.md)

PR Description
--------------

Still a WIP
Closes: #14 

Implements various scoring mechanisms so that we can perform SKLearn's GridSearchCV.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/adam2392/mne-hfo/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

2021-02-17 19:43 UTC, adam2392 commented on mne_hfo/posthoc.py
> +    dc = ["onset", "duration"]
Eventually will need a description of match-true, match-pred and match-total.

2021-02-17 19:43 UTC, adam2392 commented on mne_hfo/posthoc.py
> +    # Calculate frq from dataframe, then matching window
Eventually will need a description of match-true, match-pred and match-total.

2021-02-17 19:44 UTC, adam2392 commented on mne_hfo/posthoc.py
> +    # Calculate frq from dataframe, then matching window
Also describe what is returned. I'm assuming a structured dataframe, or is it a list?

2021-02-17 19:53 UTC, adam2392 reviewed
The question I have is how do we go from:

```
expected_dict_true = {
        "true_index": [0, 1, 2, 3],
        "pred_index": [0, 1, None, 2]
    }
```
to a prediction score? Does one just convert true_index -> ytrue (all 1's). How can we encompass a false-negative (i.e. an HFO that is not actually present in the reference dataset)?

2021-02-17 20:22 UTC, adam2392 commented
true positive rate (recall), false discovery rate, precision, kappa score

2021-02-18 01:52 UTC, adam2392 commented on mne_hfo/scores.py
> +def accuracy(y, y_pred):
All of these functions require certain columns inside, so this should be error checked.

2021-02-18 01:53 UTC, adam2392 commented on mne_hfo/scores.py
> +        Annotation Dataframe with actual labels
Technically, DataFrame with `ypred index` and ytrue index columns that mean ... 
not the Annotation Dataframe.

2021-02-18 02:53 UTC, adam2392 requested changes
In ` tests/test_posthoc.py`, I think now we can add a test:

```Python
from sklearn.metrics import make_scorer

@pytest.parametrize(scorer, [<the 3 different scores>])
def test_hyperparameter_search_cv(scorer):
parameters = {'threshold': [1,2,3], ...}
detector = SomeDetector()
scorer = make_scorer(scorer, <arguments>)
cv = GridSearchCV(detector, parameters, scoring=scorer, cv=dummycv)

# use test dataset and trim down to like... 10 seconds and maybe add 1-2 artifical HFOs
cv.fit(raw, true_hfo_df)

# add checks
```

To make a dummy cv object: https://stackoverflow.com/questions/44636370/scikit-learn-gridsearchcv-without-cross-validation-unsupervised-learning

2021-02-18 15:11 UTC, pmyers16 commented on mne_hfo/scores.py
> +        Annotation Dataframe with actual labels
These are the annotation dataframes. Matching occurs in the scoring function. Would you prefer another way?

2021-02-18 15:17 UTC, pmyers16 commented on mne_hfo/scores.py
> +        Annotation Dataframe with actual labels
Sorry these are event dataframes, I will change

2021-02-18 15:35 UTC, adam2392 commented on mne_hfo/scores.py
> +        Annotation Dataframe with actual labels
Sorry I meant that these can be annotation data frames (not events please for the sake of consistency) but that they don't really require anything beyond two columns right?

These two columns encode some sort of data that allows you to then compute said metric. 

So it would be good to have a description of what those two columns are. Can be copy pasted

2021-02-19 05:05 UTC, adam2392 commented
# Making SearchCV work
So in order to make GridSearch work, we need to change the way we structure input into the `fit()` function. Some minor changes:

1. For raw data: we want channels to correspond to `n_samples` in sklearn, and time points to correspond to `n_features`.
2. For "y" labeled data: we want a list that is `n_samples` long. That is each channel will get a list now of HFO endpoints. Example:

```Python
# has length equal to number of channels
# the second channel has no HFOs detected
y = [[(0, 20), (10, 40), ...], [], [(20, 30), (10, 20), ...], ...]]  
```

For example, try out the `test_hyperparameter_search_cv` with accuracy just returning dummy "1" rn. It should work. 

# Suggestions and comments
In order to make code easier to maintain and build upon and testable, here are a few comments:

1. Only use `annotations.tsv style DataFrame`: we aren't using the events dataframe format. I simply have that for legacy pulling over from the Fedele / other datasets that store things in the events.tsv files. Might even make those private eventually. In all dataframe functions, assume annotations because one then has the channels column. 
2. `match_detections` does not fit into the above structure: I know it's a "functional" working fucntion, but I can't figure out how it works. I think this needs to be refactored to fit in line with the working data structure assumptions of the rest of the repository (i.e. annotations-style DataFrame). 
3. As a result, of the above 2, the scoring functions are not easy to work with if one starts from Annotations DataFrames. Ideally, one can just feed in 2 annotations.tsv files formatted according to BIDS and a score can be computed. 

I made a new `match_detected_annotations` function inside `posthoc.py:L341`, which I would like you to implement and test. Once you have that working, then everything else should work.

# Next Steps

- [ ] Implement `match_detected_annotations`
- [ ] Test `match_detected_annotations`
- [ ] Implement scoring functions (FYI, see `_compute_score_data()` function.

2021-02-19 17:17 UTC, pmyers16 commented on mne_hfo/scores.py
> +    # y = _make_ydf_sklearn(y, ch_names=)
Im confused by your psuedocode here. If y is a df, the check that it is valid. If it is not a df, then pass it to _make_ydf_sklearn. But that function takes a df (which we just checked that it isnt) and outputs a list of list of tuples. Wouldn't we want it the other way around? If a list of list of tuples is passed in, convert to a dataframe that we can match?

2021-02-19 17:35 UTC, adam2392 commented on mne_hfo/scores.py
> +    # y = _make_ydf_sklearn(y, ch_names=)
Oh yeah sorry this isn't pseudocode, just didn't have anything here.

Once `match_annotations` is done, then this should as you say:
- check if it's a dataframe, if so, check that it's the correct type of dataframe
- if it's a list, assume that it's a list of HFO events, which needs to then get converted to an annotations dataframe. In doing so, one needs to pass in the `ch_names` that corresponds to the list of HFO events. 

^ the fact that you need to pass in a list, is a bit lame, so I'm wondering if instead we should be be making `_make_y_sklearn` output an OrderedDictionary.

2021-02-19 19:22 UTC, pmyers16 commented on mne_hfo/scores.py
> +    # y = _make_ydf_sklearn(y, ch_names=)
So we can handle this two ways. Have the scoring functions take kwargs of ch_name and sfreq, or use an OrderedDictionary where the keys are ch_names and sfreq is some dummy value like 1 just to get around the requirement since its not actually used. Or I suppose we could use an OrderedDictionary with sfreq as a kwarg

2021-02-22 04:10 UTC, adam2392 commented
I made some fixes (minor), such as removing the `dc=['onset', 'offset']` stuff. Just explicitly set these columns as numeric, and compute `offset = onset + duration`. Each dataframe can be assumed to be in `Annotations` format.

- I'm going to remove the need for `ch_names` in the scoring, and add a private function to go from OrderedDictionary of sklearn compatible data structure -> Annotations DF.

### A few questions:

1. I'm not sure why you had to add the `filter_band` to LineLengthDetector in the test
2. Why did you have to add `sfreq` to the scorers?

2021-02-23 19:22 UTC, adam2392 commented
Can you update `whats_new.rst` and then this should be good to go?

Else if you also want to add the additional step to the notebook showing the gridsearchCV performance on the reference Fedele dataset, then you can do that here.

2021-02-25 02:26 UTC, adam2392 commented on tests/test_posthoc.py
> +# @pytest.mark.skip()
Let's just delete all this now, that we have a tested and working version of match_annotations

2021-02-25 02:29 UTC, adam2392 requested changes
Can you just migrate all cells for running on simulation to another notebook under `tutorials/` and rename "basic_compute_hfos.ipynb" to "compute_hfos_on_fedele_dataset.ipynb"?

2021-02-25 15:38 UTC, adam2392 approved these changes

2021-02-25 15:48 UTC, merged